--- #YAML:1.0
name:                POE-Component-WWW-Search-Mininova
version:             0.03
abstract:            non-blocking POE wrapper for
license:             ~
author:              
    - Zoffix Znet <zoffix@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    POE:                           0.9999
    POE::Filter::Line:             1.192
    POE::Filter::Reference:        1.2187
    POE::Wheel::Run:               1.2179
    WWW::Search::Mininova:         0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
